package com.commands;

public enum CommandType {
    ADD, CLEAR, COUNT_GR_THAN_PRICE, COUNT_LESS_THAN_VENUE, EXECUTE_SCRIPT, HELP, INFO, REMOVE_ANY_BY_RF,
    REMOVE_BY_ID, REMOVE_LOWER, SHOW, SORT, UPDATE_ID, EXIT
}